services:

  postgres:
    image: postgres:15
    container_name: dockerbdcalendario
    environment:
      POSTGRES_DB: festivos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  mongodb:
    image: mongo:6
    container_name: mongodb_festivos
    ports:
      - "27017:27017"